export type Person = {
  id: number;
  name: string;
  display_name: string;
  avatar: string;
  banned: boolean;
  published: string;
  updated: string;
  actor_id: string;
  bio: string;
  local: boolean;
  banner: string;
  deleted: boolean;
  inbox_url: string;
  shared_inbox_url: string;
  matrix_user_id: string;
  bot_account: boolean;
  ban_expires: string;
  instance_id: number;
};
